name: movies
description: Application to view movies.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  
  dio: ^3.0.10
  dartz: ^0.9.2
  mobx: ^1.2.1+4
  intl: ^0.16.1
  google_fonts: ^1.1.1
  connectivity: ^2.0.2
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^2.0.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mockito: ^4.1.3  
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #